apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar-pod
  name: sidecar-pod
  namespace: lab3
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do date >> /var/log/date.log; sleep 5; done
    image: busybox
    name: busybox
    volumeMounts:
    - name: workdir
      mountPath: /var/log
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    hostPath:
      path: /var/log
      type: DirectoryOrCreate
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
